CREATE TABLE employees (
    id SERIAL PRIMARY KEY,
    name TEXT,
    marriedid INT,
    maritalstatusid INT,
    genderid INT,
    empstatusid INT,
    deptid INT,
    perfscoresid INT,
    fromdiversityjobfairid INT,
    salary NUMERIC,
    termd BOOLEAN,
    positionid INT,
    position TEXT,
    state TEXT,
    zip TEXT,
    dob DATE,
    sex TEXT,
    maritaldesc TEXT,
    citizendesc TEXT,
    hispaniclatino BOOLEAN,
    racedesc TEXT,
    dateofhire DATE,
    dateoftermination DATE,
    termreason TEXT,
    employmentstatus TEXT,
    department TEXT,
    managername TEXT,
    managerid INT,
    recruitmentsource TEXT,
    performancescore TEXT,
    engagementsurvey NUMERIC,
    empsatisfaction NUMERIC,
    specialprojectscount INT,
    lastperformancereview_date DATE,
    dayslatelast30 INT,
    absences INT
);

COPY employees(
    name,
    marriedid,
    maritalstatusid,
    genderid,
    empstatusid,
    deptid,
    perfscoresid,
    fromdiversityjobfairid,
    salary,
    termd,
    positionid,
    position,
    state,
    zip,
    dob,
    sex,
    maritaldesc,
    citizendesc,
    hispaniclatino,
    racedesc,
    dateofhire,
    dateoftermination,
    termreason,
    employmentstatus,
    department,
    managername,
    managerid,
    recruitmentsource,
    performancescore,
    engagementsurvey,
    empsatisfaction,
    specialprojectscount,
    lastperformancereview_date,
    dayslatelast30,
    absences
)
FROM '/docker-entrypoint-initdb.d/HRDataset_v14.csv'
DELIMITER ',' CSV HEADER;


